image: Visual Studio 2017

clone_folder: '%USERPROFILE%\go\src\github.com\topfreegames\libpitaya'

environment:
  nodejs_version: "Current"
  matrix:
    - PYTHON: "C:\\Python38-x64"
      PYTHON_ARCH: "64"

build:
  verbosity: detailed

configuration: Release

platform: x64

artifacts:
  - path: 'build\Release\*.dll'
    name: Dlls

  - path: 'build\Release\*.lib'
    name: Libs

install:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"

before_build:
  - cd %USERPROFILE%\go\src\github.com\topfreegames\libpitaya
  - SET PATH=%PYTHON%;%PATH%
  - echo %PATH%
  - dir %PYTHON%
  - python3 pip install conan
  - conan install . -if build
  - cmake -H. -Bbuild -G "Visual Studio 15 2017 Win64" -DBUILD_SHARED_LIBS=ON
  - cd build

build_script:
  - cmake --build . --config Release

after_build:
  - dir Release

deploy:
  description: 'Release'
  provider: GitHub
  draft: true
  auth_token:
    secure: "zZylescCEij0QU44MySw8xIQgBjmRJfD/p/42ddQQoxLoFzC4TP+kkZm3ywsrKo6"
  artifact: /.*\.dll|.*\.lib/
  on:
    appveyor_repo_tag: true

