language: c
compiler: clang

env:
  - GOPATH=~/go

services:
  - docker

matrix:
  include:
    # -----------------------
    # LINUX (building for android)
    # -----------------------
    - os: linux
      dist: trusty
      addons:
        apt:
          update: true
          packages:
            - ninja-build
      sudo: required
      install: 
        - cd ~
        - curl https://dl.google.com/android/repository/android-ndk-r17b-linux-x86_64.zip -o android-ndk-r17b.zip
        - unzip -qo android-ndk-r17b.zip
        - cd $TRAVIS_BUILD_DIR
      before_script: 
        - mkdir -p build
        - cd build
        - cmake -GNinja -DPITAYA_LIB_TYPE=SHARED -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=~/android-ndk-r17b/build/cmake/android.toolchain.cmake -DANDROID_ABI=armeabi-v7a ..
      script:
        - cmake --build .
      deploy:
        provider: releases
        draft: true
        skip_cleanup: true
        target_commitish: $TRAVIS_COMMIT
        tag_name: $TRAVIS_TAG
        api_key:
          secure: K7JbFSr7j5TSzbaFRrizO9MFQbYccfhldmMbgA5u23NROE5xKP4DcAfA1qDYjhz+ur/X8l4dogOTZn5AAgR/NMdELnPiU/6fyGJlzXa8lheYUoei5pUTlJCRX+YIKUalHc4rVFlhiS7NnVE4iZwK2xlgKyfImntAWrk4hgjaSoJB6x67I7pJVJM9aA+pDusoqR1G62PP99oPw29TEr9ttOTc/d0rgQFkjPs2v7vDttlPRqsfXdLXVDD/hz/nWB3AQ4Y3jMLPfrc17PWWixVnkzAPnB3Eoz3D4DQrXxYnMzM6Cis0haCVayEpu5ZoVwVBWNldtYui/qd/14xU/NBMFIn7ClB3WpzbfsLzBaa+pbNtr/CjPgRyBNP70D+cb3h2TDpvwCUvecImaC1RdNJSkqtqWYmryPcZMuDXQns91NRVLLXwnsTmw/CyXsdLP4/KMHgr/kERsb3Pde92L///mvcl/lDI/p/a8IZHRm9IDedqlG5aG2YEJUMoTXqCW7c9Ntpp9/bognLICff3twjkbDuHY9h2G+NA/dP3az52R3vA2I74BgcUDUINVUvGzScJc6nrhifHZugcR8mr8od8wPvIZReFzFv+ND0aquqtZRVb5kUl4RZkwwFfJ4vWB/bLVSxwT80k/83tKjEdC6L5rMO3QdE5thTEwa3rF0Bc35s=
        file_glob: true
        file: 
          - '*android.so'
          - '*.zip'
        on:
          repo: topfreegames/libpitaya
          tags: true
          condition: $(../release.py check --against "$TRAVIS_TAG") == ""

    # -----------------------
    # LINUX
    # -----------------------
    - os: linux
      dist: trusty
      addons:
        apt:
          update: true
          packages:
            - ninja-build
      sudo: required
      before_install:
        - mkdir -p ~/go/src/github.com/topfreegames
        - mv $TRAVIS_BUILD_DIR/../libpitaya ~/go/src/github.com/topfreegames
        - export TRAVIS_BUILD_DIR=~/go/src/github.com/topfreegames/libpitaya
        - cd $TRAVIS_BUILD_DIR
      install: 
        - eval "$(GIMME_GO_VERSION=1.10 gimme)"
        - make setup-node-linux

        - cd ~/go/src/github.com/topfreegames
        - git clone https://github.com/topfreegames/pitaya
        - cd pitaya
        - go get -u github.com/golang/dep/cmd/dep
        - ~/go/bin/dep ensure

        - cd ~/go/src/github.com/topfreegames/libpitaya
        - (cd pitaya-servers/json-server && go get)
        - (cd pitaya-servers/protobuf-server && go get)
        - docker run -p 4222:4222 -d --name nats-main nats
        - docker run -d -p 2379:2379 -p 2380:2380 appcelerator/etcd

        - ./build-openssl.py --force --prefix openssl-build --openssl-tar deps/openssl-OpenSSL_1_0_1u.tar.gz linux
      before_script: 
        - mkdir -p build && cd build
        - cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DPITAYA_LIB_TYPE=SHARED ..
      script: 
        - cmake --build .
        - sudo cp libpitaya-linux.so /usr/lib
        - cd ..
        - ./run-tests.py --node-path ~/node/bin/node --go-path ~/.gimme/versions/go1.10.linux.amd64/bin/go
      deploy:
        provider: releases
        draft: true
        skip_cleanup: true
        target_commitish: $TRAVIS_COMMIT
        tag_name: $TRAVIS_TAG
        api_key:
          secure: K7JbFSr7j5TSzbaFRrizO9MFQbYccfhldmMbgA5u23NROE5xKP4DcAfA1qDYjhz+ur/X8l4dogOTZn5AAgR/NMdELnPiU/6fyGJlzXa8lheYUoei5pUTlJCRX+YIKUalHc4rVFlhiS7NnVE4iZwK2xlgKyfImntAWrk4hgjaSoJB6x67I7pJVJM9aA+pDusoqR1G62PP99oPw29TEr9ttOTc/d0rgQFkjPs2v7vDttlPRqsfXdLXVDD/hz/nWB3AQ4Y3jMLPfrc17PWWixVnkzAPnB3Eoz3D4DQrXxYnMzM6Cis0haCVayEpu5ZoVwVBWNldtYui/qd/14xU/NBMFIn7ClB3WpzbfsLzBaa+pbNtr/CjPgRyBNP70D+cb3h2TDpvwCUvecImaC1RdNJSkqtqWYmryPcZMuDXQns91NRVLLXwnsTmw/CyXsdLP4/KMHgr/kERsb3Pde92L///mvcl/lDI/p/a8IZHRm9IDedqlG5aG2YEJUMoTXqCW7c9Ntpp9/bognLICff3twjkbDuHY9h2G+NA/dP3az52R3vA2I74BgcUDUINVUvGzScJc6nrhifHZugcR8mr8od8wPvIZReFzFv+ND0aquqtZRVb5kUl4RZkwwFfJ4vWB/bLVSxwT80k/83tKjEdC6L5rMO3QdE5thTEwa3rF0Bc35s=
        file_glob: true
        file: '*linux.so'
        on:
          repo: topfreegames/libpitaya
          tags: true
          condition: $(./release.py check --against "$TRAVIS_TAG") == ""

    # -----------------------
    # MAC
    # -----------------------
    - os: osx
      osx_image: xcode9
      sudo: required
      install:
        - brew update
        - brew install ninja
      before_script: 
        - mkdir -p build && cd build
        - cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DPITAYA_LIB_TYPE=MODULE ..
      script: 
        - cmake --build .
      deploy:
        provider: releases
        draft: true
        skip_cleanup: true
        target_commitish: $TRAVIS_COMMIT
        tag_name: $TRAVIS_TAG
        api_key:
          secure: K7JbFSr7j5TSzbaFRrizO9MFQbYccfhldmMbgA5u23NROE5xKP4DcAfA1qDYjhz+ur/X8l4dogOTZn5AAgR/NMdELnPiU/6fyGJlzXa8lheYUoei5pUTlJCRX+YIKUalHc4rVFlhiS7NnVE4iZwK2xlgKyfImntAWrk4hgjaSoJB6x67I7pJVJM9aA+pDusoqR1G62PP99oPw29TEr9ttOTc/d0rgQFkjPs2v7vDttlPRqsfXdLXVDD/hz/nWB3AQ4Y3jMLPfrc17PWWixVnkzAPnB3Eoz3D4DQrXxYnMzM6Cis0haCVayEpu5ZoVwVBWNldtYui/qd/14xU/NBMFIn7ClB3WpzbfsLzBaa+pbNtr/CjPgRyBNP70D+cb3h2TDpvwCUvecImaC1RdNJSkqtqWYmryPcZMuDXQns91NRVLLXwnsTmw/CyXsdLP4/KMHgr/kERsb3Pde92L///mvcl/lDI/p/a8IZHRm9IDedqlG5aG2YEJUMoTXqCW7c9Ntpp9/bognLICff3twjkbDuHY9h2G+NA/dP3az52R3vA2I74BgcUDUINVUvGzScJc6nrhifHZugcR8mr8od8wPvIZReFzFv+ND0aquqtZRVb5kUl4RZkwwFfJ4vWB/bLVSxwT80k/83tKjEdC6L5rMO3QdE5thTEwa3rF0Bc35s=
        file_glob: true
        file: '*.bundle'
        on:
          repo: topfreegames/libpitaya
          tags: true
          condition: $(../release.py check --against "$TRAVIS_TAG") == ""

    # -----------------------
    # MacOS (building for iOS)
    # -----------------------
    - os: osx
      osx_image: xcode9
      sudo: required
      install:
        - brew update
        - brew install ninja
        - brew upgrade python
      before_script: 
        - mkdir -p build && cd build
        - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=../cmake/ios.toolchain.cmake -DPITAYA_LIB_TYPE=STATIC ..
      script:
        - cmake --build .
      deploy:
        provider: releases
        draft: true
        skip_cleanup: true
        target_commitish: $TRAVIS_COMMIT
        tag_name: $TRAVIS_TAG
        api_key:
          secure: K7JbFSr7j5TSzbaFRrizO9MFQbYccfhldmMbgA5u23NROE5xKP4DcAfA1qDYjhz+ur/X8l4dogOTZn5AAgR/NMdELnPiU/6fyGJlzXa8lheYUoei5pUTlJCRX+YIKUalHc4rVFlhiS7NnVE4iZwK2xlgKyfImntAWrk4hgjaSoJB6x67I7pJVJM9aA+pDusoqR1G62PP99oPw29TEr9ttOTc/d0rgQFkjPs2v7vDttlPRqsfXdLXVDD/hz/nWB3AQ4Y3jMLPfrc17PWWixVnkzAPnB3Eoz3D4DQrXxYnMzM6Cis0haCVayEpu5ZoVwVBWNldtYui/qd/14xU/NBMFIn7ClB3WpzbfsLzBaa+pbNtr/CjPgRyBNP70D+cb3h2TDpvwCUvecImaC1RdNJSkqtqWYmryPcZMuDXQns91NRVLLXwnsTmw/CyXsdLP4/KMHgr/kERsb3Pde92L///mvcl/lDI/p/a8IZHRm9IDedqlG5aG2YEJUMoTXqCW7c9Ntpp9/bognLICff3twjkbDuHY9h2G+NA/dP3az52R3vA2I74BgcUDUINVUvGzScJc6nrhifHZugcR8mr8od8wPvIZReFzFv+ND0aquqtZRVb5kUl4RZkwwFfJ4vWB/bLVSxwT80k/83tKjEdC6L5rMO3QdE5thTEwa3rF0Bc35s=
        file_glob: true
        file:
          - 'deps/libuv/*.a'
          - 'deps/zlib/*.a'
          - '*.a'
        on:
          repo: topfreegames/libpitaya
          tags: true
          condition: $(../release.py check --against "$TRAVIS_TAG") == ""

after_script:
  - ls

before_deploy:
  - git config --local user.name "Travis Bot"
  - git config --local user.email "<>"
