language: c
compiler: clang

# go:
# - 1.9.2

matrix:
  include:
    # -----------------------
    # LINUX
    # -----------------------
    - os: linux
      dist: trusty
      addons:
        apt:
          update: true
          packages:
            - ninja-build
      sudo: required
      install: make install-gyp
      before_script: make gyp-linux
      deploy:
        provider: releases
        draft: true
        skip_cleanup: true
        target_commitish: $TRAVIS_COMMIT
        tag_name: $TRAVIS_TAG
        api_key:
          secure: K7JbFSr7j5TSzbaFRrizO9MFQbYccfhldmMbgA5u23NROE5xKP4DcAfA1qDYjhz+ur/X8l4dogOTZn5AAgR/NMdELnPiU/6fyGJlzXa8lheYUoei5pUTlJCRX+YIKUalHc4rVFlhiS7NnVE4iZwK2xlgKyfImntAWrk4hgjaSoJB6x67I7pJVJM9aA+pDusoqR1G62PP99oPw29TEr9ttOTc/d0rgQFkjPs2v7vDttlPRqsfXdLXVDD/hz/nWB3AQ4Y3jMLPfrc17PWWixVnkzAPnB3Eoz3D4DQrXxYnMzM6Cis0haCVayEpu5ZoVwVBWNldtYui/qd/14xU/NBMFIn7ClB3WpzbfsLzBaa+pbNtr/CjPgRyBNP70D+cb3h2TDpvwCUvecImaC1RdNJSkqtqWYmryPcZMuDXQns91NRVLLXwnsTmw/CyXsdLP4/KMHgr/kERsb3Pde92L///mvcl/lDI/p/a8IZHRm9IDedqlG5aG2YEJUMoTXqCW7c9Ntpp9/bognLICff3twjkbDuHY9h2G+NA/dP3az52R3vA2I74BgcUDUINVUvGzScJc6nrhifHZugcR8mr8od8wPvIZReFzFv+ND0aquqtZRVb5kUl4RZkwwFfJ4vWB/bLVSxwT80k/83tKjEdC6L5rMO3QdE5thTEwa3rF0Bc35s=
        file_glob: true
        file: build/out/Release_x64/output/*.so
        on:
          repo: topfreegames/libpitaya
          tags: true

    # -----------------------
    # MAC
    # -----------------------
    - os: osx
      osx_image: xcode9
      sudo: required
      install:
        - brew update
        - brew install ninja
        - make install-gyp
      before_script: make gyp-ios-mac
      deploy:
        provider: releases
        draft: true
        skip_cleanup: true
        target_commitish: $TRAVIS_COMMIT
        tag_name: $TRAVIS_TAG
        api_key:
          secure: K7JbFSr7j5TSzbaFRrizO9MFQbYccfhldmMbgA5u23NROE5xKP4DcAfA1qDYjhz+ur/X8l4dogOTZn5AAgR/NMdELnPiU/6fyGJlzXa8lheYUoei5pUTlJCRX+YIKUalHc4rVFlhiS7NnVE4iZwK2xlgKyfImntAWrk4hgjaSoJB6x67I7pJVJM9aA+pDusoqR1G62PP99oPw29TEr9ttOTc/d0rgQFkjPs2v7vDttlPRqsfXdLXVDD/hz/nWB3AQ4Y3jMLPfrc17PWWixVnkzAPnB3Eoz3D4DQrXxYnMzM6Cis0haCVayEpu5ZoVwVBWNldtYui/qd/14xU/NBMFIn7ClB3WpzbfsLzBaa+pbNtr/CjPgRyBNP70D+cb3h2TDpvwCUvecImaC1RdNJSkqtqWYmryPcZMuDXQns91NRVLLXwnsTmw/CyXsdLP4/KMHgr/kERsb3Pde92L///mvcl/lDI/p/a8IZHRm9IDedqlG5aG2YEJUMoTXqCW7c9Ntpp9/bognLICff3twjkbDuHY9h2G+NA/dP3az52R3vA2I74BgcUDUINVUvGzScJc6nrhifHZugcR8mr8od8wPvIZReFzFv+ND0aquqtZRVb5kUl4RZkwwFfJ4vWB/bLVSxwT80k/83tKjEdC6L5rMO3QdE5thTEwa3rF0Bc35s=
        file_glob: true
        file:
          - build/out/Release_x64/output/*.a
          - build/out/Release_x64/output/*.bundle
        on:
          repo: topfreegames/libpitaya
          tags: true

script:
  - make build

after_script:
  - ls build/out/Release_x64/output

before_deploy:
- git config --local user.name "Travis Bot"
- git config --local user.email "<>"
