services:
  nats:
    image: nats
    ports:
      - 4222:4222
  etcd:
    image: quay.io/coreos/etcd:v3.5.15
    command: >
      /usr/local/bin/etcd
      --data-dir=/etcd-data
      --name node1
      --initial-advertise-peer-urls http://0.0.0.0:2380
      --listen-peer-urls http://0.0.0.0:2380
      --advertise-client-urls http://0.0.0.0:2379
      --listen-client-urls http://0.0.0.0:2379
      --initial-cluster node1=http://0.0.0.0:2380
    ports:
      - 2379:2379
      - 2380:2380
  protoserver:
    build:
      dockerfile: ./Dockerfile.ProtobufServer
    ports:
      - 3350:3350
      - 3351:3351
      - 3352:3352
  jsonserver:
    build:
      dockerfile: ./Dockerfile.JsonServer
    ports:
      - 3250:3250
      - 3251:3251
      - 3252:3252
